language: node_js
node_js:
  - "0.12"
before_install: npm install -g grunt-cli
install: npm install
script: grunt install
after_success:
    - grunt deploy
branches:
  only:
    - master
    - development
